image: gitpod/workspace-node:22

tasks:
  - name: Setup and build
    init: |
      corepack enable || true
      npm ci
      npm run build
    command: npm test -- --runInBand

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - EditorConfig.EditorConfig
    - eamodio.gitlens
